input_dim: [192]
output_dim: [10]
nlayers: [3]
hidden_structure: ['constant']
hidden_factor1: [0.75, 1.25, 0.1]
hidden_factor2: [None]
dropout_probs: [0, 0.5, 0.25]
bnorms: [True, False]
init_scheme: ['xavier', 'standard']
activation: ['relu', 'tanh']
end_activation: ['softmax']
