input_dim: [192]
output_dim: [10]
nlayers: [3]
hidden_structure: ['decreasing']
hidden_factor1: [0.5, 0.6, 0.1]
hidden_factor2: [0.6, 0.75, 0.05]
dropout_probs: [0, 0.5, 0.25]
bnorms: [True, False]
init_scheme: ['xavier', 'standard']
activation: ['relu', 'tanh']
end_activation: ['softmax']
