input_dim: [192]
output_dim: [10]
nlayers: [3]
hidden_structure: ['convex']
hidden_factor1: [0.3, 0.5, 0.1]
hidden_factor2: [1.2, 1.4, 0.1]
dropout_probs: [0, 0.5, 0.25]
bnorms: [True, False]
init_scheme: ['xavier', 'standard']
activation: ['relu', 'tanh']
end_activation: ['softmax']
